### ISSUE TITLE
How To Make Plugins For Enve?

### ISSUE THREAD

**Issue by mihadalam56** [axiomgraph/Plugins-for-enve-2d#2]
Hey, Can you make a tutorial on how to make plugins for enve in your youtube channel on English Language?

**Comment by RaSeHo** [comment]
It's not a plugin at all. It's just a shader and no more.

**Comment by mihadalam56** [comment]
> It's not a plugin at all. It's just a shader and no more.

So how can someone make a shader for enve and use it on windows?

**Comment by axiomgraph** [comment]
> So how can someone make a shader for enve and use it on windows?
currently I have no idea how to make it work on windows. and also you can create your own plugins(fragment shaders). there are lot of videos available  on YouTube. you can use this playlist as starting point https://youtube.com/playlist?list=PL4neAtv21WOmIrTrkNO3xCyrxg4LKkrF7 (Lewis Lepton) and https://maurycyliebner.github.io/docs/shaderEffects
and rewriting shadertoy codes will also work on enve.

**Comment by mihadalam56** [comment]
> > So how can someone make a shader for enve and use it on windows?
> > currently I have no idea how to make it work on windows. and also you can create your own plugins(fragment shaders). there are lot of videos available  on YouTube. you can use this playlist as starting point https://youtube.com/playlist?list=PL4neAtv21WOmIrTrkNO3xCyrxg4LKkrF7 (Lewis Lepton) and https://maurycyliebner.github.io/docs/shaderEffects
> > and rewriting shadertoy codes will also work on enve.

I have used your shaders on windows and it (all of them) works perfectly. so i guess making them on linux or windows doesn't matter. I think eve uses external gpu to use the shaders

**Comment by axiomgraph** [comment]
> > > So how can someone make a shader for enve and use it on windows?
> > > currently I have no idea how to make it work on windows. and also you can create your own plugins(fragment shaders). there are lot of videos available  on YouTube. you can use this playlist as starting point https://youtube.com/playlist?list=PL4neAtv21WOmIrTrkNO3xCyrxg4LKkrF7 (Lewis Lepton) and https://maurycyliebner.github.io/docs/shaderEffects
> > > and rewriting shadertoy codes will also work on enve.
> 
> I have used your shaders on windows and it (all of them) works perfectly. so i guess making them on linux or windows doesn't matter. I think eve uses external gpu to use the shaders

Impressive. Last time I checked on Windows 10, it threw me some errors.

**Comment by mihadalam56** [comment]
> > > > So how can someone make a shader for enve and use it on windows?
> > > > currently I have no idea how to make it work on windows. and also you can create your own plugins(fragment shaders). there are lot of videos available  on YouTube. you can use this playlist as starting point https://youtube.com/playlist?list=PL4neAtv21WOmIrTrkNO3xCyrxg4LKkrF7 (Lewis Lepton) and https://maurycyliebner.github.io/docs/shaderEffects
> > > > and rewriting shadertoy codes will also work on enve.
> > 
> > 
> > I have used your shaders on windows and it (all of them) works perfectly. so i guess making them on linux or windows doesn't matter. I think eve uses external gpu to use the shaders
> 
> Impressive. Last time I checked on Windows 10, it threw me some errors.

i had them too. when I tried it for the first time on a PC without any external gpu it showed me some critical error. but when i got a gpu (nvidia gt730) and tried to install them nothing showed and it worked.

**Comment by mihadalam56** [comment]
Sure! Can't wait to try them :)
