### ISSUE TITLE
Shader Effects Error on Windows 10

### ISSUE THREAD

**Issue by freewarecamp** [axiomgraph/Plugins-for-enve-2d#3]
Hello Axiomgraph, I tried your new shaders (dirblur,glitch2,bloom,swirl) on windows 10 with gpu gt730 and all of them showed critical error except the swirl effect :(
all the error massages were same. I hope you can fix them :)
![error](https://user-images.githubusercontent.com/86367188/200807426-55d94cd4-ab12-4a56-bd09-dce5880e7422.png)

**Comment by axiomgraph** [comment]
fixed can you check it again. also I created a separate folder for windows users.

**Comment by freewarecamp** [comment]
the old problem is fixed i guess, now it is showing another error. 

![image](https://user-images.githubusercontent.com/86367188/201064324-dbfb949b-0f2d-4f0a-bc16-686afe58de92.png)

**Comment by axiomgraph** [comment]
can you check again from "for windows users".

**Comment by axiomgraph** [comment]
![Screenshot 2022-11-10 at 19-43-57 axiomgraph_Plugins-for-enve-2d addons for enve 2d for creating different effects](https://user-images.githubusercontent.com/68183694/201114609-973b1cbd-a42a-46f6-8d76-c32762fc4264.png)

**Comment by freewarecamp** [comment]
I used the files from 'for windows user' folder and that was the new error

> the old problem is fixed i guess, now it is showing another error.
> 
> ![image](https://user-images.githubusercontent.com/86367188/201064324-dbfb949b-0f2d-4f0a-bc16-686afe58de92.png)

**Comment by axiomgraph** [comment]
what enve version are you using. it looks fine on my computer (Intel HD Graphics)
![enve](https://user-images.githubusercontent.com/68183694/201338444-061c6c46-03b6-4a94-8c22-32d6f756f336.PNG)

**Comment by freewarecamp** [comment]
crap! i was using a older version, i uninstalled it and installed the latest version but still having the error :(

**Comment by freewarecamp** [comment]
here is a recording... now i think my pc is missing some kind of .dll file or vc redistributable........ don't know XD

https://user-images.githubusercontent.com/86367188/201344122-6e85a6b8-ca06-4563-a09b-9d7dfcede250.mp4

**Comment by freewarecamp** [comment]
i did it now im having new error....
![image](https://user-images.githubusercontent.com/86367188/201460324-2c36814a-9284-4975-a81a-4951f2be806f.png)

![image](https://user-images.githubusercontent.com/86367188/201460372-5ab98223-b3b4-44a6-82ea-c66200924048.png)

somebody save me................... X(

**Comment by freewarecamp** [comment]
i did that totally wrong, i tried again with no mistake and this is what im having now X(
![image](https://user-images.githubusercontent.com/86367188/201460737-53d27832-0e24-455a-a7b9-7b995dd38b71.png)

**Comment by freewarecamp** [comment]
wtf just happend XD. I deleted all of them from shadereffect path and copied them from the orginal file and guess what all of them are working! XD. I guess the shadereffect path was messed up. Never mind me, Keep Making these effects and take my love brother :)


![image](https://user-images.githubusercontent.com/86367188/201460996-ef133965-3166-41d3-b504-38d802554e0a.png)

**Comment by axiomgraph** [comment]
if you got any new errors in future. please let me know.
